{
 "title": "Control D Exporter Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "orgID",
    "label": "Organization ID",
    "query": {
     "query": "label_values(controld_profile_preset_filters_total,orgId)"
    }
   },
   {
    "name": "profileName",
    "label": "Profile Name",
    "query": {
     "query": "label_values(controld_profile_preset_filters_total,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Control D Exporter Dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard visualize Control D metrics served from Control D API.\n\n- Please fetch the metrics using https://github.com/umatare5/controld-exporter.\n"
   }
  },
  {
   "title": "DNS Service Health",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_network_health_code{service_name=\"dns\"}",
     "legendFormat": "{{city_name}}"
    }
   ]
  },
  {
   "title": "API Service Health",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_network_health_code{service_name=\"api\"}",
     "legendFormat": "{{city_name}}"
    }
   ]
  },
  {
   "title": "Next Billing Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_billing_subscription_nextbill_timestamp * 1000"
    }
   ]
  },
  {
   "title": "Billing Transaction Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "controld_billing_status" }
   ]
  },
  {
   "title": "Billing Refund Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "controld_billing_refunded" }
   ]
  },
  { "title": "Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Number of Billable Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "hosts" } },
   "targets": [
    {
     "expr": "controld_endpoint_clients_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  {
   "title": "Subscription Amount / USD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "controld_billing_subscription_amount_total{currency=\"USD\"}",
     "legendFormat": "{{currency}}"
    }
   ]
  },
  {
   "title": "Subscription Amount / JPY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "expr": "controld_billing_subscription_amount_total{currency=\"JPY\"}",
     "legendFormat": "{{currency}}"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Profile Settings Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_profile_content_filters_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Contents"
    },
    {
     "expr": "controld_profile_enabled_option_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Options"
    },
    {
     "expr": "controld_profile_groups_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Groups"
    },
    {
     "expr": "controld_profile_ip_filters_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - IPFilters"
    },
    {
     "expr": "controld_profile_preset_filters_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Presets"
    },
    {
     "expr": "controld_profile_rules_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Rules"
    },
    {
     "expr": "controld_profile_services_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Services"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "controld_profile_content_filters_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Contents"
    },
    {
     "expr": "controld_profile_enabled_option_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Options"
    },
    {
     "expr": "controld_profile_groups_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Groups"
    },
    {
     "expr": "controld_profile_ip_filters_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - IPFilters"
    },
    {
     "expr": "controld_profile_preset_filters_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Presets"
    },
    {
     "expr": "controld_profile_rules_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Rules"
    },
    {
     "expr": "controld_profile_services_total{orgId=~\"$orgID\", name=~\"$profileName\"}",
     "legendFormat": "{{orgId}}: {{name}} - Services"
    }
   ]
  },
  {
   "title": "Registered Service Categories Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 30 },
   "targets": [
    {
     "expr": "controld_service_categories_total{orgId=~\"$orgID\"}",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  { "title": "Organization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_organization_users_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_organization_members_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_organization_profiles_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_organization_routers_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  {
   "title": "Sub Orgs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_organization_sub_orgs_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  { "title": "Sub Organization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_sub_organization_users_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_sub_organization_members_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_sub_organization_routers_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controld_sub_organization_profiles_total",
     "legendFormat": "{{orgId}}: {{name}}"
    }
   ]
  }
 ]
}