name: Release Application

on:
  push:
    branches: ["main"]
    paths: ["VERSION"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  tagging:
    uses: umatare5/common/.github/workflows/tagging.yml@v0.9.0

  release:
    uses: umatare5/common/.github/workflows/go-release.yml@v0.9.0
    with:
      go_version: "1.24.5"
      goreleaser_version: "v2.11.1"
