name: Release Application to ghcr.io and Artifacts

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    uses: umatare5/common/.github/workflows/goreleaser.yml@9d2100ae23eab16f883991b17ff4efc19560d5da # v0.2.0
    with:
      go_version: "1.24.5"
      goreleaser_version: "v2.11.1"
