name: Lint Code with golangci-lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: umatare5/common/.github/workflows/golangci-lint.yml@9d2100ae23eab16f883991b17ff4efc19560d5da # v0.2.0
    with:
      go_version: "1.24.5"
      golangci_lint_version: "v1.64.8"
      golangci_lint_config: ".golangci.yml"
