name: Lint Code with golangci-lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: umatare5/common/.github/workflows/golangci-lint.yml@7a4932187171f01b7cec6ed9cb8d94040c7e604e
    with:
      go_version: "1.24.5"
      golangci_lint_version: "v1.64.8"
      golangci_lint_config: ".golangci.yml"
