name: Lint Code with golangci-lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: umatare5/common/.github/workflows/golangci-lint.yml@8591a02d1a57f8c3ecac195457aa1bdeb82a30e4 # v0.3.0
    with:
      go_version: "1.24.5"
      golangci_lint_version: "v1.64.8"
      golangci_lint_config: ".golangci.yml"
