name: Release Application to ghcr.io and Artifacts

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    uses: umatare5/common/.github/workflows/goreleaser.yml@7a4932187171f01b7cec6ed9cb8d94040c7e604e
    with:
      go_version: "1.24.5"
      goreleaser_version: "v2.11.1"
