name: Release Application to ghcr.io and Artifacts

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    uses: umatare5/common/.github/workflows/goreleaser.yml@8591a02d1a57f8c3ecac195457aa1bdeb82a30e4 # v0.3.0
    with:
      go_version: "1.24.5"
      goreleaser_version: "v2.11.1"
