name: Release Application to ghcr.io and Artifacts

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    uses: umatare5/common/.github/workflows/goreleaser.yml@3045bfd35340e4ec3f08989c03e6c672008b4709
    with:
      go_version: "1.24.5"
      goreleaser_version: "v2.11.1"
